package enhancer;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Enlogin extends javax.swing.JFrame {

    public Enlogin() {
        initComponents();
        this.setSize(430, 280);
        this.setTitle("IMAGE ENHANCER");
        Dimension sd = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(sd.width / 2 - this.getWidth() / 2, sd.height / 2 - this.getHeight() / 2);
        tpass.setEchoChar('*');
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bok = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tpass = new java.awt.TextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        bexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        bok.setBackground(new java.awt.Color(255, 102, 255));
        bok.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bok.setText("OK");
        bok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bokActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("password :-");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(20, 60, 120, 40);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("User Name :-");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 20, 130, 40);

        tname.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        tname.setText("Enhancer");
        jLayeredPane1.add(tname);
        tname.setBounds(140, 30, 210, 30);
        jLayeredPane1.add(tpass);
        tpass.setBounds(140, 70, 180, 30);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(20, 20, 390, 126);

        jLayeredPane2.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bexit.setBackground(new java.awt.Color(255, 102, 255));
        bexit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bexit.setText("Exit");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        jLayeredPane2.add(bexit);
        bexit.setBounds(210, 30, 100, 30);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(20, 150, 390, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/im8.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 410, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_bexitActionPerformed

    private void bokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bokActionPerformed
        // TODO add your handling code here:
        if (tpass.getText().equals("1234")) {
            Enmenu menu = new Enmenu();
            menu.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(new Enlogin(), "PLEASE ENTER THE CORRRECT PASSWORD");
            tpass.setText("");
            tpass.requestFocus();
        }
}//GEN-LAST:event_bokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Enlogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton bok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JTextField tname;
    private java.awt.TextField tpass;
    // End of variables declaration//GEN-END:variables
}
