package enhancer;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


import java.io.File;
import org.opencv.core.Size;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import static org.opencv.imgproc.Imgproc.medianBlur;

public class Enpreprocess extends javax.swing.JFrame {

    
    JFileChooser fc;
    String dcode, dpath, directory, filename;
    File[] listOfFiles;
    File file;

    
    public Enpreprocess() {
        initComponents();
        this.setSize(1200, 620);
        this.setTitle("IMAGE ENHANCER");
        Dimension sd = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(sd.width / 2 - this.getWidth() / 2, sd.height / 2 - this.getHeight() / 2);

        // Load the native library.
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

        System.out.println("OpenCV library loaded");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        tpath = new javax.swing.JTextField();
        bfile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdata = new javax.swing.JTextArea();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        bstart = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("IMAGE PREPROCESSING USING MEDIAN FILTER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 20, 1120, 40);

        jLayeredPane2.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Folder Name :-");
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(10, 40, 180, 30);

        tpath.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLayeredPane2.add(tpath);
        tpath.setBounds(200, 40, 260, 30);

        bfile.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        bfile.setText("Get Image Folder For Preprocessing");
        bfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfileActionPerformed(evt);
            }
        });
        jLayeredPane2.add(bfile);
        bfile.setBounds(470, 40, 450, 29);

        tdata.setBackground(new java.awt.Color(0, 0, 0));
        tdata.setColumns(20);
        tdata.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        tdata.setForeground(new java.awt.Color(255, 0, 51));
        tdata.setRows(5);
        jScrollPane1.setViewportView(tdata);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(200, 80, 720, 280);

        getContentPane().add(jLayeredPane2);
        jLayeredPane2.setBounds(10, 70, 1140, 380);

        jLayeredPane3.setBackground(new java.awt.Color(255, 0, 0));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bstart.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        bstart.setText("START PREPROCESS");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });
        jLayeredPane3.add(bstart);
        bstart.setBounds(430, 20, 170, 30);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jLayeredPane3.add(Back);
        Back.setBounds(30, 20, 80, 23);

        getContentPane().add(jLayeredPane3);
        jLayeredPane3.setBounds(10, 470, 1140, 70);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1180, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed

        for (File file1 : listOfFiles) {
            if (file1.isFile()) {

                System.out.println(file1.getName());
                //tdata.append("\n" + tpath.getText() + "\\" + file1.getName());
                 Mat im = Imgcodecs.imread(tpath.getText() + "\\" + file1.getName());
                Mat dst = new Mat();
                Mat dst1 = new Mat();
                Mat dst2 = new Mat();
               //Size sz = new Size(100,100);
                Imgproc.medianBlur(im, dst, 5);
                Imgproc.resize(dst, dst1, new Size(dst.cols()/2,  dst.rows()/2),0.0,0.0,4);                
                Imgproc.resize(dst1, dst2, new Size(dst.cols(),  dst.rows()),0.0,0.0,4);
                Imgcodecs.imwrite("C:/Users/Masoom/Desktop/pratham/files/lr images/LR" + file1.getName(), dst2);
            }
        }
        JOptionPane.showMessageDialog(new Enpreprocess(), "IMAGE PREPROCESSING COMPLETED");


}//GEN-LAST:event_bstartActionPerformed

    private void bfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfileActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(Enpreprocess.this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getCurrentDirectory();
            tpath.setText(file.getPath());

            File folder = new File(tpath.getText());
            listOfFiles = folder.listFiles();
            tdata.setText("");
            for (File file1 : listOfFiles) {
                if (file1.isFile()) {

                    //System.out.println(file1.getName());
                    tdata.append("\n" + tpath.getText() + "\\" + file1.getName());

                }
            }

        }


    }//GEN-LAST:event_bfileActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Enpreprocess().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton bfile;
    private javax.swing.JButton bstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tdata;
    private javax.swing.JTextField tpath;
    // End of variables declaration//GEN-END:variables
}
